### ISSUE TITLE
update task comment during svn commit

### ISSUE THREAD

**Issue by onkelDad** [redminenb/redminenb#28]
Hi,

We use svn out of netbeans and would like to use the feature of netbeans to update redmine issues including the svn-commit message (see screenshots).
The redmine plugin open the selected issue after svn-commit, but do not add the comment as specified.

regards,
Detlef Urban

![redminenb-svn-commit](https://cloud.githubusercontent.com/assets/9032283/6263778/c2eefc14-b81c-11e4-9a6d-92a4ed41d20a.PNG)
![redminenb-svn-issue-comment](https://cloud.githubusercontent.com/assets/9032283/6263789/f0da0e7a-b81c-11e4-8fd3-c9132b728273.PNG)

**Comment by matthiasblaesing** [comment]
You are right! This bug happens in the case, that you do not choose the "Resolve as FIXED" option. In that case the operation turns into a noop, as the update is not done.

The fix was committed as:

https://github.com/redminenb/redminenb/commit/10b6ac08e3f247d298e2e4b1b17bf644b43e98a1

It will be part of the next release. I'll have to see, when I can cut one, as I don't want to flood the plugin center helpers, that clear the updates.
